server:
      port: 9001
spring:
    application:
      name: ihrm-company #指定服务名
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/saas-ihrm?useUnicode=true&characterEncoding=utf8&useSSL=false
      # data-username:
      password: root
      username: root
    jpa:
      database: mysql
      show-sql: true
      open-in-view: true
